resolver: lts-9.21

packages:
- location: .
- location: ../dispenser-core
  extra-dep: true
# - location:
#     git: git@dispenser-core.github.com:SuperpowersCorp/dispenser-core.git
#     commit: 81753b5ba6dd9a86d7d5991a6e24b231e0568974
#   extra-dep: true

extra-deps:
- monad-io-adapter-0.1.0.0
- protolude-0.2.1
- safe-exceptions-0.1.7.0
